# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: false

controller_frequency: 3.0
controller_patience: 3.0


planner_frequency: 0.0
planner_patience: 0.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

max_planning_retries: 1

# local planner - default is trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"
#base_local_planner: "teb_local_planner/TebLocalPlannerROS" "dwa_local_planner/DWAPlannerROS"

base_global_planner: "youibot_rrt/RRTPlanner" 
#alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner


#We plan to integrate recovery behaviors for turtlebot but currently those belong to gopher and still have to be adapted.
## recovery behaviors; we avoid spinning, but we need a fall-back replanning
recovery_behavior_enabled: false
reset_distance: 1.0
