set(_CATKIN_CURRENT_PACKAGE "youibot_rrt")
set(youibot_rrt_VERSION "0.0.0")
set(youibot_rrt_MAINTAINER "Sikai Xiao <sxiao@jhu.edu>")
set(youibot_rrt_PACKAGE_FORMAT "2")
set(youibot_rrt_BUILD_DEPENDS "roscpp" "roslint" "tf" "nav_core" "costmap_2d" "base_local_planner" "pluginlib" "eigen" "visualization_msgs" "nav_core")
set(youibot_rrt_BUILD_EXPORT_DEPENDS )
set(youibot_rrt_BUILDTOOL_DEPENDS "catkin")
set(youibot_rrt_BUILDTOOL_EXPORT_DEPENDS )
set(youibot_rrt_EXEC_DEPENDS "nav_core" "roscpp" "pluginlib" "costmap_2d" "base_local_planner" "nav_core" "tf" "eigen" "visualization_msgs")
set(youibot_rrt_RUN_DEPENDS "nav_core" "roscpp" "pluginlib" "costmap_2d" "base_local_planner" "tf" "eigen" "visualization_msgs")
set(youibot_rrt_TEST_DEPENDS "gtest" "rostest")
set(youibot_rrt_DOC_DEPENDS "doxygen")
set(youibot_rrt_URL_WEBSITE "")
set(youibot_rrt_URL_BUGTRACKER "")
set(youibot_rrt_URL_REPOSITORY "https://github.com/jeshoward/turtlebot_rrt")
set(youibot_rrt_DEPRECATED "")